name: Lint
permissions:
  contents: read
  pull-requests: write
on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  resolve-modules:
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-24.04, ubuntu-24.04-arm]
    name: resolve module
    runs-on: ${{ matrix.runner }}
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - id: set-matrix
        run: ./hack/resolve-modules.sh

  lint:
    name: lint module
    runs-on: ${{ matrix.runner }}
    needs: resolve-modules
    strategy:
      matrix: ${{ fromJson(needs.resolve-modules.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.6
          working-directory: ${{ matrix.workdir }}
